name: Example Docker action
description: Example Docker action
inputs:
  var1:
    description: Some variable 1
    required: true
  var2:
    description: Some variable 2
    required: false
    default: var2_COMMON
  number:
    description: Guess the number
    required: false
    default: '-1'
outputs:
  guessed-number:
    description: Whether guessed the number
runs:
  image: Dockerfile
  using: docker