name: Demo - environment variables and secrets
on:
  push:
#    branches:
#      - master
env:
  ENV_ALL: GLOBAL env all
  ENV_JOB: GLOBAL env job
  ENV_STEP: GLOBAL env step
jobs:
  no-shading:
    runs-on: ubuntu-latest
    steps:
      - name: Print env variables
        run: |
          echo "ENV_ALL = $ENV_ALL"
          echo "ENV_JOB = $ENV_JOB"
          echo "ENV_STEP = $ENV_STEP"
          echo "ENV_UNSET = $ENV_UNSET"
  shade-on-job:
    runs-on: ubuntu-latest
    env:
      ENV_ALL: JOB env all
      ENV_JOB: JOB env job
      ENV_STEP: JOB env step
    steps:
      - name: Print env variables
        run: |
          echo "ENV_ALL = $ENV_ALL"
          echo "ENV_JOB = $ENV_JOB"
          echo "ENV_UNSET = $ENV_UNSET"
  shade-on-job-and-step:
    runs-on: ubuntu-latest
    env:
      ENV_ALL: JOB env all
      ENV_JOB: JOB env job
      ENV_STEP: JOB env step
    steps:
      - name: Print env variables
        env:
          ENV_ALL: STEP env all
          ENV_JOB: STEP env step
          ENV_STEP: STEP env step
        run: |
          echo "ENV_ALL = $ENV_ALL"
          echo "ENV_JOB = $ENV_JOB"
          echo "ENV_STEP = $ENV_STEP"
          echo "ENV_UNSET = $ENV_UNSET"
  test:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Print env variables
        run: echo "ENV_ALL = $ENV_ALL"
      #      - name: Download source code
      #        uses: actions/checkout@v3
      #      - name: Setup Java
      #        uses: actions/setup-java@v3
      #        with:
      #          distribution: temurin
      #          java-version: 17
      #          cache: gradle
      #      - name: Test project
      #        run: gradle test
      - name: Output information
        run: echo "..."
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Print env variables
        env:
          ENV_STEP: STEP env step
        run: |
          echo "ENV_ALL = $ENV_ALL"
          echo "ENV_JOB = $ENV_JOB"
          echo "ENV_STEP = $ENV_STEP"
      - name: Output information
        run: |
          echo "..."
