name: Demo - using matrix (same workflow, different inputs)
on:
  #  push:
  workflow_dispatch:
jobs:
  workflow-description:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow description
        run: |
          echo ---
          echo 'Shows usage of matrix - a feature to test job(s) with different input parameters combinations'
          echo Generally all possible input combinations will happen
          echo '  e.g. If you have 2 parameters, one with 2 inputs, another with 3 - the job will run 6 times'
          echo It's also possible to include or exclude specific combinations manually
          echo ---
  some-job:
    continue-on-error: true
    strategy:
      matrix:
        java: [ 17 ]
        runner: [ ubuntu-latest, windows-latest ]
        include:
          - java: 19
            runner: ubuntu-latest
        exclude:
          - java: 17
            runner: windows-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Print matrix parameters
        run: echo "Job called with java = ${{matrix.java}}; runner = ${{matrix.runner}}"