name: Demo - environment variables and secrets
on:
  push:
#    branches:
#      - master
env:
  ENV_VAR: GLOBAL
jobs:
  no-shading:
    runs-on: ubuntu-latest
    steps:
      - name: Print env variables
        run: echo '$ENV_VAR = '"$ENV_VAR"'; $''{{env.ENV_VAR}} = '"${{env.ENV_VAR}}"
  shade-on-job:
    runs-on: ubuntu-latest
    env:
      ENV_VAR: JOB
    steps:
      - name: Print env variables
        run: echo '$ENV_VAR = '"$ENV_VAR"'; $''{{env.ENV_VAR}} = '"${{env.ENV_VAR}}"
  shade-on-job-and-step:
    runs-on: ubuntu-latest
    env:
      ENV_VAR: JOB
    steps:
      - name: Print env variables
        env:
          ENV_VAR: STEP
        run: echo '$ENV_VAR = '"$ENV_VAR"'; $''{{env.ENV_VAR}} = '"${{env.ENV_VAR}}"
  test:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Print env variables
        run: echo '$ENV_VAR = '"$ENV_VAR"'; $''{{env.ENV_VAR}} = '"${{env.ENV_VAR}}"
      - name: Download source code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Test project
        run: gradle test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Print env variables
        run: echo '$ENV_VAR = '"$ENV_VAR"'; $''{{env.ENV_VAR}} = '"${{env.ENV_VAR}}"
      - name: Output information
        run: |
          echo "..."
