name: Demo - conditional jobs/steps, continue-on-error
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download source code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Run tests
        id: run-tests
        run: gradle test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports/tests/test/*
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Print echo
        run: echo ...
  success-report:
    needs: [ test, deploy ]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Print report
        run: echo "Success report"
  job-with-failed-step-and-continue-on-error:
    runs-on: ubuntu-latest
    steps:
      - name: Purposefully fail this step
        continue-on-error: true
        run: exit 1
      - name: Next step after failing
        run: echo "Standard next step after failing"
