name: Demo - using reusable workflow
on:
  push:
#    branches:
#      - master
jobs:
  use-composed-action:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Use custom action
        uses: ./.github/actions/example-composed-action
        with:
          var1: var1_STEP