name: Demo on how script injection (threat) can happen
on:
  issues:
    types:
      - opened
  push:
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Print instruction
        run: echo "Create an issue entitled, e.g. 'a";echo I have executed a script!"'
      - name: Assign label
        run: |
          issue-title="${{github.event.issue.title}}"
          if [["$issue.title" == *"bug"*]]; 
          then
            echo "Issue is a bug"
          else
            echo "Issue is NOT a bug"
          fi