name: Demo - using reusable workflow
on:
  push:
    branches:
      - master
jobs:
  use-composed-action-as-job:
    uses: ./.github/actions/example-composed-action/action.yml
    with:
      var1: var1_JOB
  use-composed-action-as-step:
    runs-on: ubuntu-latest
    steps:
      - name: Use custom action
        uses: ./.github/actions/example-composed-action/action.yml
        with:
          var1: var1_STEP