name: Demo - on Issues action
on:
  #  issues:
  workflow_dispatch:
jobs:
  output_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: |
          echo Issue: "${{github.event.issue.title}}"
          echo "${{toJSON(github.event.changes)}}"
          
          
