name: Demo - artifacts, outputs
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download source code
        uses: actions/checkout@v3
      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          args: "--replace"
          skipCommit: true
      - name: Print format diffs
        run: git --no-pager diff --exit-code
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run unit tests
        run: ./gradlew test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download source code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build project
        run: ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build artifacts
          path: build/libs/*
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: Build artifacts
      - name: Output artifact contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
