name: 'Example composed action'
description: Simple action to show how it's done
inputs:
  var1:
    description: Some variable 1
    required: true
  var2:
    description: Some variable 2
    required: false
    default: var2_COMMON
  number:
    description: Guess the number
    required: false
    default: '-1'
outputs:
  guessed-number:
    description: Whether guessed the number
    value: ${{steps.guessed-number.guessed}}
runs:
  using: composite
  steps:
    - name: Print build number
      shell: bash
      run: echo 'Build number:' "${{github.run_number}}"
    - name: Print variables
      shell: bash
      run: |
        echo "var1 = ${{inputs.var1}}"
        echo "var2 = ${{inputs.var2}}"
    - name: Return whether guessed the number
      id: guessed-number
      shell: bash
      run: |
        if [[ $number == '10' ]]
        then 
          guessed=true 
        else 
          guessed=false 
        fi
        echo $guessed
        echo "guessed=$guessed" >> $GITHUB_OUTPUT
